---
- hosts: elevate
  vars:
    project_path: /opt/frontend/mentorED-Portal
    root_path: /opt/frontend
  tasks:
    - name: Slurp hosts file
      slurp:
        src: "/opt/backend/deployment/.token"
      register: slurpfile
    - name: Run vault credentials
      shell: "curl --location --request GET '{{ vaultAddress }}mentored-portal' --header 'X-Vault-Token: {{ slurpfile['content'] | b64decode }}' | jq '.data' > '{{root_path}}/data2.json'"
      register: vaultCurl
    - name: Change directory
      shell: cd {{project_path}}
    - name: pull latest code
      git:
        repo: https://github.com/ELEVATE-Project/mentorED-Portal.git
        dest: "{{ project_path }}"
        version: "{{ gitBranch }}"
        force: yes
    - name: Update npm
      shell: npm i --force
    - name: set permission
      shell: chmod 744 {{ project_path }}/src/scripts/json2env.sh  
    - name: generate .env
      shell: cat {{root_path}}/data2.json | {{ project_path }}/src/scripts/json2env.sh > {{ project_path }}/src/environments.ts
      register: envConfig 
    - debug: msg=" cred {{ envConfig }} "
    - name: Change directory
      shell: chdir {{project_path}}
    - name: Get pm2 file
      shell: "curl --location --request GET '{{ vaultAddress }}portalPm2Config' --header 'X-Vault-Token: {{ slurpfile['content'] | b64decode }}' | jq '.data' > '{{ project_path }}/pm2.config.json'"
      register: pm2
    - name: Change dir
      shell: cd {{ project_path }}
      - name: Build portal
      shell: npm run build:ssr
    - name: Start pm2
      shell: cd {{ project_path }} && pm2 start pm2.config.json --name='MentorEd-Portal'